services:
  - type: web
    name: apistosos-api
    env: python
    region: oregon     
    plan: free
    
    rootDir: app 
    
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"